window.RL_DATA = {
  meta: {
    edition: "Summer 2026",
    update: "",
    label: "Ranking startowy",
    updatedAt: "4 sierpnia 2026",
    verificationNote: "Składy Summer są oficjalnie zgłoszone."
  },
  sources: [
    { label: "LoL Esports", url: "https://lolesports.com/pl-PL/leagues/first_stand%2Cmsi%2Crift_legends%2Cworlds", note: "wyniki i terminarz" },
    { label: "Leaguepedia", url: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split", note: "składy i role" },
    { label: "GOL.GG", url: "https://gol.gg/esports/home/", note: "statystyki meczowe" },
    { label: "Rift Legends", url: "https://x.com/RiftLegendsPL", note: "komunikaty ligi" },
    { label: "Nervarien", url: "https://www.youtube.com/@nervarien", note: "transmisje" }
  ],
  broadcasts: {
    youtubeLive: "https://www.youtube.com/watch?v=WFGNForUKn0",
    youtubeChannel: "https://www.youtube.com/@nervarien",
    twitch: "https://www.twitch.tv/nervarien"
  },
  weights: [
    { label: "Skład", value: 30, note: "poziom i doświadczenie zawodników" },
    { label: "Wyniki", value: 20, note: "ostatnie oficjalne serie" },
    { label: "Przeciwnicy", value: 15, note: "siła rozegranych rywali" },
    { label: "Zgranie", value: 15, note: "ciągłość i współpraca składu" },
    { label: "Forma", value: 10, note: "ostatnie występy" },
    { label: "Długie serie", value: 10, note: "gra w BO3 i BO5" }
  ],
  teams: [
    {
      rank: 2,
      name: "BOMBA Team",
      short: "BOMBA",
      mark: "BT",
      logo: "assets/bomba-team.webp",
      score: 90,
      trend: "↓1",
      trendLabel: "",
      tier: "S",
      state: "hot",
      accent: "#ff4d6d",
      rosterStatus: "Oficjalnie zgłoszony",
      rosterStatusType: "official",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["frajgo", "adi1", "Mrozku", "Odi11", "minemaciek"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["frajgo", "Guli", "Mrozku", "Odi11", "minemaciek"],
      previousExtras: ["LeQu"],
      previousStaff: ["Maquk", "Dylan"],
      staff: ["Maquk", "behave", "Dylan"],
      spring: "2. miejsce · Spring Playoffs 2026",
      metrics: { roster: 86, results: 92, opposition: 90, synergy: 92, form: 88, series: 92 }
    },
    {
      rank: 1,
      name: "devils.one inStreamly",
      short: "devils.one",
      mark: "DV1",
      logo: "assets/devils-one-instreamly.webp",
      score: 92,
      trend: "↑1",
      trendLabel: "NOWY LIDER",
      tier: "S",
      state: "hot",
      accent: "#ff375f",
      rosterStatus: "Oficjalnie zgłoszony",
      rosterStatusType: "official",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["iBo", "Shlatan", "iwanan", "Woolite", "Erdote"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["Goldmen", "belit", "fantomisto", "Faetski", "Calmsky"],
      previousExtras: [],
      previousStaff: ["Pavelov", "grzybarez"],
      staff: ["DzikDzikowski"],
      spring: "7. miejsce · Spring Split 2026",
      metrics: { roster: 98, results: 90, opposition: 92, synergy: 78, form: 93, series: 96 }
    },
    {
      rank: 3,
      name: "LODIS",
      short: "LODIS",
      mark: "LOD",
      logo: "assets/lodis.webp",
      score: 88,
      trend: "0",
      trendLabel: "",
      tier: "A+",
      state: "hot",
      accent: "#5aa8ff",
      rosterStatus: "Oficjalnie zgłoszony",
      rosterStatusType: "official",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["Sinmivak", "mikusik", "Czekolad", "zamulek", "Kaseko"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["Blesia", "Kokos", "lee sang", "Klorell", "Robertoos"],
      previousExtras: ["Syrpy"],
      previousStaff: ["Crystalerr"],
      staff: ["TTobias"],
      spring: "6. miejsce · Spring Split 2026",
      metrics: { roster: 96, results: 86, opposition: 88, synergy: 72, form: 88, series: 90 }
    },
    {
      rank: 4,
      name: "Forsaken",
      short: "Forsaken",
      mark: "FSK",
      logo: "assets/forsaken.webp",
      score: 87,
      trend: "0",
      trendLabel: "",
      tier: "A+",
      state: "hot",
      accent: "#9b6cff",
      rosterStatus: "Oficjalnie zgłoszony",
      rosterStatusType: "official",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["Color", "MAXI", "Decay", "Syzyfek", "Lucker"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["iBo", "XnS", "Decay", "Scorth", "Lucker"],
      previousExtras: ["Kiuske"],
      previousStaff: ["astr0less", "Gilius"],
      staff: ["Nice Guy Ben"],
      spring: "1. miejsce · Spring Playoffs 2026",
      metrics: { roster: 92, results: 87, opposition: 89, synergy: 70, form: 86, series: 91 }
    },
    {
      rank: 6,
      name: "DOCISK",
      short: "DOCISK",
      mark: "DOC",
      logo: "assets/docisk.webp",
      score: 69,
      trend: "↓1",
      trendLabel: "",
      tier: "B",
      state: "stable",
      accent: "#4cd7a5",
      rosterStatus: "Oficjalnie zgłoszony",
      rosterStatusType: "official",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["PmK", "Kokos", "Birkyy", "Anyone", "Huron"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["PmK", "FullClear", "Birkyy", "Anyone", "kubagoat"],
      previousExtras: [],
      previousStaff: ["Pokson", "Lantern"],
      staff: ["Pokson", "Lantern"],
      spring: "5. miejsce · Spring Split 2026",
      metrics: { roster: 72, results: 67, opposition: 69, synergy: 65, form: 67, series: 69 }
    },
    {
      rank: 5,
      name: "Anonymo Esports",
      short: "Anonymo",
      mark: "ANO",
      logo: "assets/anonymo-esports.webp",
      score: 72,
      trend: "↑1",
      trendLabel: "",
      tier: "B",
      state: "stable",
      accent: "#8da2ff",
      rosterStatus: "Oficjalnie zgłoszony",
      rosterStatusType: "official",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["HeSSZero", "shibi", "Sobek", "Lothen", "Czypsy"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["HeSSZero", "Joki37", "Sobek", "ejsner", "Raxxo"],
      previousExtras: [],
      previousStaff: ["Valuta", "R4T"],
      staff: ["Valuta", "R4T"],
      spring: "4. miejsce · Spring Playoffs 2026",
      metrics: { roster: 73, results: 72, opposition: 74, synergy: 68, form: 69, series: 72 }
    },
    {
      rank: 7,
      name: "Barcząca Esports",
      short: "Barcząca",
      mark: "BAR",
      logo: "assets/barczaca-esports.webp",
      score: 65,
      trend: "0",
      trendLabel: "",
      tier: "C",
      state: "unknown",
      accent: "#f7a93b",
      rosterStatus: "Oficjalnie zgłoszony",
      rosterStatusType: "official",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["Blesia", "Guli", "Xaro", "ejsner", "Robertoos"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["Agresivoo", "mikusik", "Tenshi", "Woolite", "Jactroll"],
      previousExtras: ["Artoria"],
      previousStaff: ["Shoopiltee", "Chizuoku"],
      staff: ["Shoopiltee", "Periq", "Balu"],
      spring: "3. miejsce · Spring Playoffs 2026",
      metrics: { roster: 70, results: 65, opposition: 72, synergy: 48, form: 65, series: 68 }
    },
    {
      rank: 8,
      name: "UP2UMEDIA Cebulaki",
      short: "UP2U Cebulaki",
      mark: "UP2U",
      logo: "assets/up2umedia-cebulaki.webp",
      logoInvert: true,
      score: 62,
      trend: "0",
      trendLabel: "BEZ ZMIAN",
      tier: "C",
      state: "unknown",
      accent: "#f5b942",
      rosterStatus: "Oficjalnie zgłoszony",
      rosterStatusType: "official",
      rosterSource: "Źródło: Rift Legends",
      rosterSourceUrl: "https://x.com/RiftLegendsPL/status/2084654880807862719",
      updated: "2026-08-04",
      roster: ["Hatsu", "Jacobmolly", "Salaterka", "chicase", "Envy"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "OPEN QUALIFIER 2",
      previousRoster: ["Hatsu", "Sojo", "Salaterka", "Lothen", "Envy"],
      previousExtras: [],
      extraPlayers: ["Gniotek", "caromii"],
      previousStaff: ["Valuta", "R4T"],
      staff: ["Kaczy102"],
      spring: "1. miejsce · Summer Promotion 2026",
      metrics: { roster: 58, results: 68, opposition: 48, synergy: 72, form: 69, series: 58 }
    }
  ]
};
