window.RL_DATA = {
  meta: {
    edition: "Summer 2026",
    update: "",
    label: "Ranking startowy",
    updatedAt: "4 sierpnia 2026",
    verificationNote: "Składy Summer są oficjalnie zgłoszone."
  },
  sources: [
    { label: "LoL Esports", url: "https://lolesports.com/pl-PL/leagues/first_stand%2Cmsi%2Crift_legends%2Cworlds", note: "wyniki i terminarz" },
    { label: "Leaguepedia", url: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split", note: "składy i role" },
    { label: "GOL.GG", url: "https://gol.gg/esports/home/", note: "statystyki meczowe" },
    { label: "Rift Legends", url: "https://x.com/RiftLegendsPL", note: "komunikaty ligi" },
    { label: "Nervarien", url: "https://www.youtube.com/@nervarien", note: "transmisje" }
  ],
  broadcasts: {
    youtubeChannel: "https://www.youtube.com/@nervarien",
    twitch: "https://www.twitch.tv/nervarien"
  },
  teams: [
    {
      rank: 2,
      name: "BOMBA Team",
      short: "BOMBA",
      mark: "BT",
      logo: "assets/bomba-team.webp",
      score: 84,
      trend: "↓1",
      trendLabel: "",
      tier: "S",
      state: "hot",
      accent: "#ff4d6d",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["frajgo", "adi1", "Mrozku", "Odi11", "minemaciek"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["frajgo", "Guli", "Mrozku", "Odi11", "minemaciek"],
      previousStaff: ["Maquk", "Dylan"],
      staff: ["Maquk", "behave", "Dylan"],
      achievements: [
        { kind: "title", badge: "WINTER 2026", title: "Mistrz Rift Legends Winter 2026", detail: "1. miejsce w play-offach" },
        { kind: "emea", badge: "EMEA 13-16", title: "EMEA Masters Spring 2026", detail: "13-16. miejsce" }
      ],
      spring: "2. miejsce · Spring Playoffs 2026"
    },
    {
      rank: 1,
      name: "devils.one inStreamly",
      short: "devils.one inStreamly",
      mark: "DV1",
      logo: "assets/devils-one-instreamly.webp",
      score: 86,
      trend: "↑1",
      trendLabel: "NOWY LIDER",
      tier: "S",
      state: "hot",
      accent: "#ff375f",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["iBo", "Shlatan", "iwanan", "Woolite", "Erdote"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["Goldmen", "belit", "fantomisto", "Faetski", "Calmsky"],
      previousStaff: ["Pavelov", "grzybarez"],
      staff: ["DzikDzikowski"],
      spring: "7. miejsce · Spring Split 2026"
    },
    {
      rank: 3,
      name: "LODIS",
      short: "LODIS",
      mark: "LOD",
      logo: "assets/lodis.webp",
      score: 82,
      trend: "0",
      trendLabel: "",
      tier: "A+",
      state: "hot",
      accent: "#5aa8ff",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["Sinmivak", "mikusik", "Czekolad", "zamulek", "Kaseko"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["Blesia", "Kokos", "lee sang", "Klorell", "Robertoos"],
      previousStaff: ["Crystalerr"],
      staff: ["TTobias"],
      spring: "6. miejsce · Spring Split 2026"
    },
    {
      rank: 4,
      name: "Forsaken",
      short: "Forsaken",
      mark: "FSK",
      logo: "assets/forsaken.webp",
      score: 80,
      trend: "0",
      trendLabel: "",
      tier: "A",
      state: "stable",
      accent: "#9b6cff",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["Color", "MAXI", "Decay", "Syzyfek", "Lucker"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["iBo", "XnS", "Decay", "Scorth", "Lucker"],
      previousStaff: ["astr0less", "Gilius"],
      staff: ["Nice Guy Ben"],
      achievements: [
        { kind: "title", badge: "SPRING 2026", title: "Mistrz Rift Legends Spring 2026", detail: "1. miejsce w play-offach" },
        { kind: "emea", badge: "EMEA 9-12", title: "EMEA Masters Spring 2026", detail: "9-12. miejsce" }
      ],
      spring: "1. miejsce · Spring Playoffs 2026"
    },
    {
      rank: 6,
      name: "DOCISK",
      short: "DOCISK",
      mark: "DOC",
      logo: "assets/docisk.webp",
      score: 76,
      trend: "↓1",
      trendLabel: "",
      tier: "B",
      state: "stable",
      accent: "#4cd7a5",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["PmK", "Kokos", "Birkyy", "Anyone", "Huron"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["PmK", "FullClear", "Birkyy", "Anyone", "kubagoat"],
      previousStaff: ["Pokson", "Lantern"],
      staff: ["Pokson", "Lantern"],
      spring: "5. miejsce · Spring Split 2026"
    },
    {
      rank: 5,
      name: "Anonymo Esports",
      short: "Anonymo",
      mark: "ANO",
      logo: "assets/anonymo-esports.webp",
      score: 78,
      trend: "↑1",
      trendLabel: "",
      tier: "B",
      state: "stable",
      accent: "#8da2ff",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["HeSSZero", "shibi", "Sobek", "Lothen", "Czypsy"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["HeSSZero", "Joki37", "Sobek", "ejsner", "Raxxo"],
      previousStaff: ["Valuta", "R4T"],
      staff: ["Valuta", "R4T"],
      spring: "4. miejsce · Spring Playoffs 2026"
    },
    {
      rank: 7,
      name: "Barcząca Esports",
      short: "Barcząca",
      mark: "BAR",
      logo: "assets/barczaca-esports.webp",
      score: 74,
      trend: "0",
      trendLabel: "",
      tier: "C",
      state: "unknown",
      accent: "#f7a93b",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["Blesia", "Guli", "Xaro", "ejsner", "Robertoos"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "SPRING",
      previousRoster: ["Agresivoo", "mikusik", "Tenshi", "Woolite", "Jactroll"],
      previousStaff: ["Shoopiltee", "Chizuoku"],
      staff: ["Shoopiltee", "Periq", "Balu"],
      spring: "3. miejsce · Spring Playoffs 2026"
    },
    {
      rank: 8,
      name: "UP2UMEDIA Cebulaki",
      short: "UP2U Cebulaki",
      mark: "UP2U",
      logo: "assets/up2umedia-cebulaki.webp",
      logoInvert: true,
      score: 72,
      trend: "0",
      trendLabel: "BEZ ZMIAN",
      tier: "C",
      state: "unknown",
      accent: "#f5b942",
      rosterSource: "Źródło: Leaguepedia",
      rosterSourceUrl: "https://lol.fandom.com/wiki/Rift_Legends/2026_Season/Summer_Split",
      updated: "2026-08-04",
      roster: ["Hatsu", "Jacobmolly", "Salaterka", "chicase", "Gniotek"],
      roles: ["TOP", "JGL", "MID", "ADC", "SUP"],
      previousLabel: "MANGO MUSZTARDA67",
      previousRoster: ["Hatsu", "Sojo", "Salaterka", "Lothen", "Envy"],
      previousStaff: ["Valuta", "R4T"],
      staff: ["Kaczy102"],
      spring: "1. miejsce · Summer Promotion 2026"
    }
  ]
};
